// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {arithmeticHighlighting} from "./highlight"
export const parser = LRParser.deserialize({
  version: 14,
  states: "#SQVQPOOOVQPO'#C^QbQPOOOOQO'#Cc'#CcOOQO'#Cd'#CdOOQO'#Cm'#CmOOQO'#Ch'#ChOOQO,58x,58xOVQPO,58yOVQPO,58zOVQPO,58{OVQPO,58|OpQPO1G.eOOQO1G.f1G.fO!RQPO1G.gO!dQPO1G.h",
  stateData: "!x~OZOS~O]PObROcSO~O]XO^WO_YO`ZO~O]XO_YO`ZOXRi^Ri~O]XOXTi^Ti_Ti`Ti~O]XOXUi^Ui_Ui`Ui~Ocb~",
  goto: "!VbPPccccckkPPPsPPPPc]UOPWXYZ]TOPWXYZQQOQVPQ[WQ]XQ^YR_Z",
  nodeNames: "⚠ Expr Neg Add Sub Mul Div Int Float",
  maxTerm: 19,
  propSources: [arithmeticHighlighting],
  skippedNodes: [0],
  repeatNodeCount: 0,
  tokenData: "$]~R`X^!Tpq!Tz{!x{|!}}!O#S!O!P#X!P!Q#{!Q![$Q#y#z!T$f$g!T#BY#BZ!T$IS$I_!T$I|$JO!T$JT$JU!T$KV$KW!T&FU&FV!T~!YYZ~X^!Tpq!T#y#z!T$f$g!T#BY#BZ!T$IS$I_!T$I|$JO!T$JT$JU!T$KV$KW!T&FU&FV!T~!}O_~~#SO^~~#XO]~~#[P!Q![#_~#dRc~!Q![#_!g!h#m#X#Y#m~#pP!Q![#s~#xPc~!Q![#s~$QO`~~$VQb~!O!P#X!Q![$Q",
  tokenizers: [0],
  topRules: {"Expr":[0,1]},
  tokenPrec: 83
})
